# Generated by Django 6.0.6 on 2026-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.TextField(verbose_name='Libelé')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
