# Generated by Django 6.0.6 on 2026-06-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gare_name', models.CharField(max_length=70)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100)),
                ('gare_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_fin', to='accounts.gare')),
                ('gare_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gare_départ', to='accounts.gare')),
            ],
        ),
        migrations.CreateModel(
            name='Syndicat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_syndic', models.CharField(max_length=30)),
                ('num_tel', models.IntegerField()),
                ('date_de_création', models.DateTimeField(auto_now_add=True)),
                ('gare_associé', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gare')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('num_tel', models.IntegerField(max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('W', 'Wave'), ('O', 'ORANGE'), ('M', 'MOOV')], max_length=2)),
                ('User_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('plaque', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('date_de_mise_en_circulation', models.DateField()),
                ('type_car', models.CharField(max_length=20)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('nombres_de_places', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('A', 'Active'), ('S', 'Suspended'), ('U', 'Used')], default='S', max_length=1)),
                ('line_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_ticket', to='accounts.line')),
                ('user_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='accounts.user')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_ticket', to='accounts.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('W', 'Wave'), ('O', 'ORANGE'), ('M', 'MOOV')], max_length=2)),
                ('vehicule_pay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='vehicule_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('Plaque_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicule')),
                ('User_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Syndicat_gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gare')),
                ('syndic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.syndicat')),
            ],
            options={
                'unique_together': {('gare', 'syndic')},
            },
        ),
    ]
