# Generated by Django 6.0.6 on 2026-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gare_line_syndicat_user_payment_user_vehicule_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='-'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_tel',
            field=models.IntegerField(),
        ),
    ]
